# Generated by Django 5.1.2 on 2024-10-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='addons',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='improvements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='opportunity',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='strengths',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='threat',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='weakness',
            field=models.JSONField(),
        ),
        migrations.AlterModelTable(
            name='studentreport',
            table='swotanalysis',
        ),
    ]
